# This workflow integrates ShiftLeft with GitHub Actions
# Visit https://docs.shiftleft.io for help
name: Analyze with ShiftLeft

on:
  pull_request:
  workflow_dispatch:
jobs:
  NextGen-Static-Analysis:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Download ShiftLeft cli
      run: |
        Invoke-WebRequest -Uri 'https://cdn.shiftleft.io/download/sl-latest-windows-x64.zip' -OutFile sl.zip
        Expand-Archive -Path sl.zip -DestinationPath .
    - name: Build WebGoat.NET
      run: dotnet build WebGoat.NET
    - name: Analyze with inspect
      run: .\sl analyze --sca --app WebGoat.NET --tag branch=$Env:GITHUB_REF --verbose --oss-recursive --oss-project-dir WebGoat --csharp --dotnet-core --cpg WebGoat/WebGoat.NET.csproj
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
